"""empty message

Revision ID: edc492faa8d0
Revises: 31a133f5e181
Create Date: 2023-08-27 17:59:36.552503

"""

# revision identifiers, used by Alembic.
revision = 'edc492faa8d0'
down_revision = '31a133f5e181'

from alembic import op
import sqlalchemy as sa
import sqlmodel


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genomes', schema=None) as batch_op:
        batch_op.create_unique_constraint('ix_genome_name_unique_constraint', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genomes', schema=None) as batch_op:
        batch_op.drop_constraint('ix_genome_name_unique_constraint', type_='unique')

    # ### end Alembic commands ###